apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hybrid-planner.fullname" . }}-api
  labels:
    {{- include "hybrid-planner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hybrid-planner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hybrid-planner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-prisma-database
          image: "{{ .Values.backendImage.image }}:{{ .Values.backendImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          command:
            - sh
            - -c
            - "npm run deploy-db"
          env:
            - name: DATABASE_URL
              value: file:/db/database.sqlite3
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backendImage.image }}:{{ .Values.backendImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              value: file:/db/database.sqlite3
            - name: URL_FRONTEND
              value: "https://planner.bricklou.ovh"
            - name: MAILHOG_HOST
              value: {{ include "hybrid-planner.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          envFrom:
            - secretRef:
                name: {{ include "hybrid-planner.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        #- name: mailhog
        # image: rollupdev/mailhog
        # ports:
        #   - name: http-mail
        #     containerPort: 8025
        #   - name: smtp-mail
        #     containerPort: 1025
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
