---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hybrid-planner.fullname" . }}
type: Opaque
stringData:
  RAINBOW_APPLICATION_ID: "{{ .Values.secrets.RAINBOW_APPLICATION_ID }}"
  RAINBOW_APPLICATION_SECRET: "{{ .Values.secrets.RAINBOW_APPLICATION_SECRET }}"
  RAINBOW_LOGIN: "{{ .Values.secrets.RAINBOW_LOGIN }}"
  RAINBOW_PASSWORD: "{{ .Values.secrets.RAINBOW_PASSWORD }}"
  JWT_SECRET: "{{ .Values.secrets.JWT_SECRET }}"
  MAIL_HOST: "{{ .Values.secrets.MAIL_HOST }}"
  MAIL_PORT: "{{ .Values.secrets.MAIL_PORT }}"
  MAIL_USER: "{{ .Values.secrets.MAIL_USER }}"
  MAIL_PASS: "{{ .Values.secrets.MAIL_PASSWORD }}"
  MAIL_DEFAULT_FROM: '{{ .Values.secrets.MAIL_FROM }}'