---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  labels:
    {{- include "hybrid-planner.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-stripeprefix
spec:
  stripPrefix:
    prefixes:
      - /api/
    forceSlash: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "hybrid-planner.fullname" . }}
  labels:
    {{- include "hybrid-planner.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: {{ .Values.ingress.hostRule }}
      services:
        - name: {{ template "hybrid-planner.fullname" . }}
          port: http-front
      middlewares:
        - name: redirect-to-https
    - kind: Rule
      match: {{ .Values.ingress.hostRule }} && PathPrefix(`/api`)
      services:
        - name: {{ template "hybrid-planner.fullname" . }}
          port: http-api
      middlewares:
        - name: redirect-to-https
        - name: api-stripeprefix