apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrid-planner.fullname" . }}
  labels:
    {{- include "hybrid-planner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontPort }}
      targetPort: http-front
      protocol: TCP
      name: http-front
    - port: {{ .Values.service.apiPort }}
      targetPort: http-api
      protocol: TCP
      name: http-api
    - port: 8025
      targetPort: http-mail
      protocol: TCP
      name: http-mail
    - port: 1025
      targetPort: smtp-mail
      protocol: TCP
      name: smtp-mail
  selector:
    {{- include "hybrid-planner.selectorLabels" . | nindent 4 }}
